### PR TITLE
Item indexes incorrect when randomised, resulting in wrong user answer saved and correct answer shown

### PR DESCRIPTION
**Pull request by andrewhosgood**
Randomised items recalled incorrect user answers as indexes were added before shuffling

### CODE REVIEW

**Comment by oliverfoster** [comment]
the index order of the original items is the only reliable way to ensure answers + items are matched. this is as the original item order doesn't change in the json only on the model after randomisation.

the original order is kept on the model items to preserve their order after randomisation. https://github.com/andrewhosgood/adapt-contrib-matching/blob/develop/js/adapt-contrib-matching.js#L32-L68


the save data is taken using the origin item indexes. https://github.com/andrewhosgood/adapt-contrib-matching/blob/develop/js/adapt-contrib-matching.js#L117

as the view is rerendered the item values are restored from the original indexes. https://github.com/andrewhosgood/adapt-contrib-matching/blob/develop/js/adapt-contrib-matching.js#L49-L68 

they are then re-shuffled (which may produce a different ending order)

if you are experiencing this problem, the logic of the implementation may be at fault but the principle is certainly correct.

this pr will break this cycle. 

have you tried with the latest spoor prs, you'll have to merge "Fix: made bit count a factor of 4" and "fix: use only questions in capture and release" into spoor to it. https://github.com/adaptlearning/adapt-contrib-spoor/pulls

there is also a fix for textInput which concerns this problem > https://github.com/adaptlearning/adapt-contrib-textInput/pulls

**Comment by oliverfoster** [comment]
If just realised you're working from sponge. Belal has been working with this a lot. I know he has a version of a poor with the fixes applied. Perhaps you could get him to +1 the PRS mentioned above? They are all fixes which came from his testing. He's also got my Skype address if you want to chat.

**Comment by andrewhosgood** [comment]
OK, understood. I thought this may not have mattered as later on the elements are referenced by the jQuery `.eq()` matcher (https://github.com/andrewhosgood/adapt-contrib-matching/blob/develop/js/adapt-contrib-matching.js#L245).

In this case I think then I shall try adding the index to the element either with the jQuery `.data()` method or with an attribute of something like `data-index` before the items are shuffled and then try referencing that in the jQuery selector that is used to show the marking. This means that when retrieving the item index (https://github.com/andrewhosgood/adapt-contrib-matching/blob/develop/js/adapt-contrib-matching.js#L218) we will get the original item index and not its shuffled index.

**Comment by oliverfoster** [comment]
sounds like a plan, although i'm still none the wiser about what the original issue was?

**Comment by andrewhosgood** [comment]
The issue was with showing marking and restoring user answers (https://github.com/andrewhosgood/adapt-contrib-matching/blob/develop/js/adapt-contrib-matching.js#L152) from each items `_selected` which wasn't being populated correctly.

**Comment by oliverfoster** [comment]
can you change the title of this pr to something more meaningful? then i'll get on to testing it.

**Comment by belal-almassri-spongeuk** [comment]
The fix for this issue is just changing the follwoing line of code :
````if (option._index == userAnswer[item._index]) ```` 
to 

````if (option._index == userAnswer[item.index]) ```` 

I will make a new pull request in a sec

**Pull request closed without merging**
